### ISSUE TITLE
ERROR: Could not install packages due to an OSError: [Errno 22] Invalid argument: '......\\torchmimic\\data\\normalizers\\decomp_ts0.8.input_str:previous.n1e5.start_time:zero.normalizer'

### ISSUE THREAD

**Issue by xueyagaga** [kingrc15/torchmimic#11]
Sorry
When I tried to install `torchmimic` on `python==3.8`, this error came out:
`ERROR: Could not install packages due to an OSError: [Errno 22] Invalid argument: '.......\\torchmimic\\data\\normalizers\\decomp_ts0.8.input_str:previous.n1e5.start_time:zero.normalizer'`
How could I deal with it?

**Comment by kingrc15** [comment]
Hi @xueyagaga, I'm sorry to hear that. It looks like you're having issues installing the normalizer data. Could you please provide additional information about your installation? Which operating system are you using, and what Python libraries do you currently have installed?
