### ISSUE TITLE
train_listfile.csv

### ISSUE THREAD

**Issue by ieee8023** [kingrc15/torchmimic#3]
When I try this code I get an error that a file `listfile.csv` is not found. It doesn't seem to be with the mimic data available from physionet. What should this file be?

```python
root_dir = "/data/mimic-iii-clinical-database-1.4/"
training_dataset = LOSDataset(root_dir, train=True)

FileNotFoundError: [Errno 2] No such file or directory: '/data/mimic-iii-clinical-database-1.4/train_listfile.csv'
```

**Comment by kingrc15** [comment]
Unfortunately this library only works with the MIMIC Benchmark datasets. The listfiles are subsets of the MIMIC-III dataset that are used for the benchmark. You can find out more about the benchmark and how to create it here: https://github.com/YerevaNN/mimic3-benchmarks
