### ISSUE TITLE
Dying kernel while loading decomposition train_listfile.csv

### ISSUE THREAD

**Issue by Bhumika-26** [kingrc15/torchmimic#5]
jupyter notebook shows "Dead kernel" while loading decomposition  'train_listfile.csv' and LOS 'train_listfile.csv'. Jupyter notebook shows the message "The kernel appears to have died. It will restart automatically."

**Comment by kingrc15** [comment]
Apologies for the delayed response. I hope you were able to resolve your issues. It seems that this might have been a problem specific to Jupyter Notebook. If you're still experiencing issues, please let us know. If we find any issues with our library, we'll be more than happy to work on resolving them.
